spring.application.name=cuenta-bancaria
spring.datasource.schema = paf

# Conexion [SQLServer] PagosAF
spring.datasource.paf.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.paf.url=jdbc:sqlserver://10.88.3.133:1433;databaseName=dbPagosAF;trustServerCertificate=true;
spring.datasource.paf.username=app_expedienteelec
spring.datasource.paf.password=IpsE2kX23..
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect